### ISSUE TITLE
漏洞

### ISSUE THREAD

**Issue by cqep** [z5882852/zhihuishu-script#5]
保存学习进度发生错误: 提交视频学习进度失败，response_code: -1, response: {"code":-1,"message":"参数解码发生错误","data":null}

出现这个错误

**Comment by z5882852** [comment]
您好，我无法复现您的问题，能否提供更详细的信息？

**Comment by z5882852** [comment]
您可以试一下重新运行，看看是否出现同样的问题。

**Comment by cqep** [comment]
> 您可以试一下重新运行，看看是否出现同样的问题。

1.还是有这个问题
2.另外大佬能不能修复一下 自动那个安全验证呢 有点麻烦，刷着刷着跳出来 不是很方便

**Comment by z5882852** [comment]
这个安全验证（网易易盾空间推理）识别需要训练模型，或者对接打码平台，以上两种方法一种耗时费力，另一种费钱。而且项目需求量也不大，没必要。

**Comment by cqep** [comment]
> 这个安全验证（网易易盾空间推理）识别需要训练模型，或者对接打码平台，以上两种方法一种耗时费力，另一种费钱。而且项目需求量也不大，没必要。

那大佬修复一下那个学习进度，保存错误就可以了

**Comment by z5882852** [comment]
解决了？

**Comment by cqep** [comment]
最近没有出现了 但是安全验证不知道怎么 明明点对了 但它偏偏说是错的
